# Generated by Django 6.0.6 on 2026-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='Phone number to receive M-Pesa payouts, format 2547XXXXXXXX.', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payout_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal')], default='mpesa', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email to receive payouts.', max_length=254),
        ),
    ]
